Ignore mypy lint errors for other files (#15266)
* Ignore mypy lint errors for other files

mypy sometimes returns errors for files that aren't the same as the file
it was called against.

This PR adds some filtering based on the current file name.

fixes https://github.com/microsoft/vscode-python/issues/10190

* use regex instead

* add news

* code review fixes

* cut new line to better match actual output

```
##########Linting Output - mypy##########
foo/__init__.py:4:5: error: Statement is unreachable  [unreachable]
foo/bar.py:2:14: error: Incompatible types in assignment (expression has type "str", variable has type "int")  [assignment]
Found 2 errors in 2 files (checked 1 source file)
```

* fix offset

* fix test?